### ISSUE TITLE
some empty lines disappear

### ISSUE THREAD

**Issue by sassbalint** [nytud/quntoken#33]
Using quntoken in emtsv we see that empty line disappears after these line-ending tokens:

/Bejátszás./

telefonon.,

legyen.-

érthető!)

**Comment by dlazesz** [comment]
Since #38 this issue does not seem to presist. @sassbalint is it still an issue? If solved, please close.

**Comment by sassbalint** [comment]
Thanks for #38. :) Did not test myself.
