### ISSUE TITLE
Furcsa, alattomos hiba: invalid character &#65279 runtime error

### ISSUE THREAD

**Issue by gpetho** [nytud/quntoken#42]
@dlazesz 

Sebességmérés közben tapasztaltam egy olyan furcsa, nehezen reprodukálható és behatárolható hibát, hogy az `emtsv tok` futásidejű hibával leáll (tehát nem csak figyelmeztet, mint normális esetben), miután "rossz" karaktert olvasott be. A hiba véletlenszerűen / nem determinisztikusan lép fel, de a hibaüzenet és a viszonylag szisztematikus jelleg alapján nem valószínű, hogy a futtató rendszerből ered, hanem programhibának tűnik.

Előzmény: https://github.com/nytud/emtsv/issues/30

Amint kiderült, a hiba a quntokenben keletkezik, és a következőképpen reprodukálható nálam. Azért ciklussal csinálom, mert egyszeri futtatás esetén hol fellép, hol nem. 10 iterációból néhány többnyire elromlik, de előfordul, hogy a tizes ciklus egyszeri futtatása nem elegendő.

### Inputfájl:
https://github.com/gpetho/rejto_rossz/blob/main/rejtorossz.txt

### CLI:
`for i in {1..10}; do quntoken <rejtorossz.txt >output.txt ; done`

Amikor egy bizonyos pontra ér a feldolgozás ebben a fájlban, a következő hibaüzenettel áll le az `stderr`-en; az output simán megszakad azon a ponton:

```
...
invalid character (27293,1): ﻿
invalid character (27679,1): ﻿
invalid character (28089,1): ﻿
invalid character (28666,1): ﻿

quex/quex/code_base/buffer/lexatoms/LexatomLoader_Converter.i:414:	terminate called after throwing an instance of 'std::runtime_error'
  what():  Converter produced BOM upon not-first call to 'convert'
Better make sure that converter NEVER produces BOM.
(May be, by specifiying the endianness of 'FromCoding' or 'ToCoding')

Aborted (core dumped)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pgergo/anaconda3/envs/emtsv1/lib/python3.6/site-packages/quntoken/quntoken.py", line 31, in stdin_writer
    stdin.writelines(inp)
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/pgergo/anaconda3/envs/emtsv1/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/pgergo/anaconda3/envs/emtsv1/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pgergo/anaconda3/envs/emtsv1/lib/python3.6/site-packages/quntoken/quntoken.py", line 31, in stdin_writer
    stdin.writelines(inp)
BrokenPipeError: [Errno 32] Broken pipe

invalid character (442,1):
...
```

Itt a végén indul a következő iteráció. A hiba véletlenszerűen lép fel, pl. ebben a konkrét ciklusban a 10 iterációból 6 állt le ezen a ponton, máskor viszont van, hogy 10-ből 0. Amikor nem lép fel a hiba, akkor ez van az `stderr`-en, és az output legenerálódik a teljes fájlra:
```
...
invalid character (27293,1): ﻿
invalid character (27679,1): ﻿
invalid character (28089,1): ﻿
invalid character (28666,1): ﻿
invalid character (28872,1): ﻿
invalid character (29346,1): ﻿
invalid character (29759,1): ﻿
...
```

### Python:

```python3
from quntoken import tokenize

for _ in range(10):
    with open('output.txt', 'w') as outfile:
        for tok in tokenize(open('rejtorossz.txt')):
            outfile.write(tok)
```

A hiba ugyanúgy jelentkezik, mint CLI-n.

### Megjegyzés:

A hibát kiváltó karakter a &#65279 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF). A furcsa és alattomos az egészben az, hogy ebben a dokumentumban 23 darab van belőle, ez a 18., a többinél soha nem állt le nekem a futás, és ennél az egynél is véletlenszerűen / nem determinisztikusan áll le, 10 iterációból talán átlag kétszer-háromszor. Próbáltam volna ennek a fájlnak kisebb részletét adni inputként (próbálkoztam pár bekezdéssel a hibás karakter körül, és azzal is, hogy a fájl első kb. felét törlöm), de úgy nem jött elő a hiba. (Illetve lehet, hogy előjönne, csak épp nem volt szerencsém.)

Próbálkoztam azzal is, amit ez ír: https://stackoverflow.com/questions/13590749/reading-unicode-file-data-with-bom-chars-in-python , tehát úgy megnyitni az inputfájlt, hogy `encoding='utf-8-sig'`, de ezzel sem változott semmi, a hiba ugyanúgy előjön.

**Comment by mittelholcz** [comment]
Már volt példa hasonló hibára, az U+200D (zero width joiner) karaktert sem kezelte jól a quex, hasonló, random hibákat dobott arra is. A preproc.qx IGNORABLE sora kezeli ezt, most bővítettem az ignorálandó karakterek listáját az U+FEFF-vel (l. [itt](https://github.com/nytud/quntoken/blob/ed4d4d5521cee83eb2d75518c43237908b19a64f/src/quex_modules/preproc.qx#L8)).

Az új releas (3.1.8) már kezeli ezt, kint van a pypi.org-on is.

Amúgy az FEFF deprecated code point a unicode 3.2. óta (ezt 2002-ben adták ki). Most már csak fájl opcionális első karktere lehet, a `zero width no-break space` helyett már [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) (`byte order mark`) funkciót tölt be. Szóval input szövegben ilyen karakternek nem kéne szerepelnie.

**Comment by dlazesz** [comment]
> a `zero width no-break space` helyett

Erre erre emlékeztem tévesen ebédnél. :)

> Amúgy az FEFF deprecated code point a unicode 3.2. óta

Jajjj de jó lesz ezt kezelni a régi szövegek esetében. ;)

Köszi a fixet Iván!

A [requirements.txt](https://github.com/nytud/emtsv/blob/master/requirements.txt)-t frissíted az emtsv-ben vagy csináljam én?
(Átadnám a lehetőséget, a cél, hogy mihamarabb legyen új release. :) )

**Comment by gpetho** [comment]
> Most már csak fájl opcionális első karktere lehet, a `zero width no-break space` helyett már [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) (`byte order mark`) funkciót tölt be. Szóval input szövegben ilyen karakternek nem kéne szerepelnie.

> Jajjj de jó lesz ezt kezelni a régi szövegek esetében. ;)

A dokumentumot konkrétan azon a napon állítottam elő, amikor jeleztem a hibát, tehát 3 napja, LibreOffice-ban.

**Comment by dlazesz** [comment]
> A dokumentumot konkrétan azon a napon állítottam elő, amikor jeleztem a hibát, tehát 3 napja, LibreOffice-ban.

Mégjobban hangzik. Lehet, hogy csak bennehagyta? Vagy biztosra tudjuk, hogy a LIbreOffice tette bele?
Az utóbbi különösen mókás lenne, de nem elképzelhetetlen.

**Comment by gpetho** [comment]
Biztos nem a LibreOffice tette bele, csak benne hagyta. Az történt, hogy néhány MEK-ből letöltött RTF-et konvertáltam txt-vé LibreOffice-ban, hogy legyen sebességmérésre egy kis korpuszom. Valószínűleg fájl első karakterei voltak eredetileg, és úgy kerültek a fájl közepébe, hogy a LibreOffice által készített txt-ket összefűztem `cat`-tal egy fájllá.

**Comment by dlazesz** [comment]
> Valószínűleg fájl első karakterei voltak eredetileg, és úgy kerültek a fájl közepébe,

Megnyugodtam. :)

> Ami ebben a formában nem túl szokatlan eljárás korpuszkészítéskor, tehát lehet rá számítani máskor is.

És mostantól működni is fog remélhetőleg. :)

Mondjuk a BOM-talanítást lehetne számonkérni a cat-on, de mindegy. (A Python mindenesetre megcsinálja, ha azzal nyitod meg a fájlokat.)

**Comment by gpetho** [comment]
> A Python mindenesetre megcsinálja, ha azzal nyitod meg a fájlokat.

A fájl belsejében levő "szabálytalan" BOM karaktereket viszont ott hagyta, ahogy írtam is.

**Comment by dlazesz** [comment]
> A fájl belsejében levő "szabálytalan" BOM karaktereket viszont ott hagyta, ahogy írtam is.

Jó tudni.

Az Unicode 3.2 kiadásának dátuma 2002-03-27. Hosszú lesz, mire kikopik ilyen sebességgel.

**Comment by mittelholcz** [comment]
@dlazesz Csinálom az emtsv frissítését.

@gpetho A libreoffice-os konverziót windowson vagy linuxon csináltad?

**Comment by gpetho** [comment]
> A libreoffice-os konverziót windowson vagy linuxon csináltad?

Linux, LibreOffice 6.4.7.2

**Comment by mittelholcz** [comment]
>Linux, LibreOffice 6.4.7.2
Köszi @gpetho, jó tudni, hogy linux-on is tesz BOM-ot a fájl elejére a LO!
